### ISSUE TITLE
Profile view: differences between EN and DE in city, twitter and website

### ISSUE THREAD

**Issue by netagonen** [rubymonsters/speakerinnen_liste#1058]
Some speakers don't have the city,  website or twitter in the EN version, and I think maybe it's not on purpose. 
Suggestions:
- Profile edit: add tooltip to translated info to explain the meaning like in the FAQ's
- move website and twitter not in the translatable part  in the form (is there something to translate there??), with city it's more complicated though

![Screenshot from 2020-03-05 18-30-47](https://user-images.githubusercontent.com/22200510/76009615-ca386e00-5f11-11ea-9494-c33270f7d6c4.png)
![Screenshot from 2020-03-05 18-31-27](https://user-images.githubusercontent.com/22200510/76009630-cf95b880-5f11-11ea-9b34-0deaa9427ed7.png)

**Comment by zaziemo** [comment]
@netagonen adding a tooltip would be good but I think people read it seldomly.
Concerning your second suggestion: the fields were moved into the translatable part because people asked for it (e.g. since they have an english speaking twitter account or website and one in their native language).

Could you explain a little bit more the problem you encounter with those empty fields? E.g. as a conference organizer I can't see the city of the speakers in the english locale. Or as a speaker I don't want to enter the same information twice....

Probably we can find another solution like creating a fallback.

**Comment by netagonen** [comment]
ok, I didn't know about the english/german twitter difference. 
My personal experience was that it's unclear. 
I also thought about what you mentioned: first, it might be annoying to insert the same info twice and that an organizer could miss speakers.

I guess we can talk about it when we meet.

**Comment by netagonen** [comment]
Hi @zaziemo , going over this again, what if we do create a fallback? 
So if some data for twitter, website and city is filled in only one language, and the speaker has profile data in both languages, we present it in the other language also?

**Comment by zaziemo** [comment]
@netagonen yes this could be possible. What about bringing this up tomorrow evening. Just to check if we don't overlook something.
