### ISSUE TITLE
Wrong speakerinnen selection when in category scope

### ISSUE THREAD

**Issue by tyranja** [rubymonsters/speakerinnen_liste#1069]
When we enter the speakerinnen overview page via the categories we get the a corret title, e.g. 'Wissenschaft & Technik' but the subsctitles count is wrong 'Wir haben 2938 Speakerinnen in der Kategorie` and the speakerinnen are all speakerinnen. We have to change that.
![Screenshot from 2020-04-11 15-07-52](https://user-images.githubusercontent.com/1218914/79044634-7bfc4600-7c06-11ea-836e-6ef14b70cdf5.png)

The subtitle should show the count of the speakerinnen in that category and the speakerinnen pofiles should also be speakerinnen in the category 'Wissenschaft & Technik"

**Comment by alonpeer** [comment]
I'm taking a look at this 👀

**Comment by alonpeer** [comment]
So yeah, the issue is that when the page https://speakerinnen.org/de/categories/11 loads, the search executed in the controller is [profiles_for_index](https://github.com/rubymonsters/speakerinnen_liste/blob/master/app/controllers/profiles_controller.rb#L182-L189), and this method doesn't take into account `param[:category_id]`. 
What's the right way of searching profiles by category ID?
