### ISSUE TITLE
Docker (compose?) doesn't work for new Apple M1 Chip

### ISSUE THREAD

**Issue by sabrina-ulbrich** [rubymonsters/speakerinnen_liste#1179]
I spend some time to get docker working with the Apple M1 chip, but it doesn't work. I found out that adding the new platform is necessary, like here: https://onexlab-io.medium.com/apple-m1-chip-no-matching-manifest-for-linux-arm64-v8-docker-mysql-5142060a9309

But in the end, elasticsearch was not working inside docker. Without docker it works.

@langjoh do you want to take a look at this?

**Comment by langjoh** [comment]
Thanks for the explanations, @sabrina-ulbrich . It would be helpful if you could specify on the following questions:
1. Do you get the same error message as in the article `no matching manifest for Linux/arm64/v8 in the manifest list entries` ? Maybe you could add a screen shot? I can't reproduce the error on my machine, that's why :)
2. Where in the docker-compose file did you add the platform? To all 3 images? Was the error message gone after that?
3. And after you added the platform, elasticsearch stopped working?

Thank you :)

**Comment by sabrina-ulbrich** [comment]
@langjoh thanks for taking care of this :)

1. Yes, I searched for this error-message. Unfortunately, I don't have a screenshot.
2. I added it to db and elastic.
3. Before I added it, nothing works. After that, postgres works and elasticsearch not.

Hope, that helps. When I now want to reproduce it, I have to do a new bundle install and stuff -- I want to avoid this, if possible.

**Comment by langjoh** [comment]
Hi @sabrina-ulbrich ,
I looked into it and, bad news first, I didn't get the Postgres images to work with the suggested ```platform: linux/amd64``` fix. 
(From what I understood after reading articles, only the Postgres Docker image is not supporting amd64 platforms) 
There are Postgres images that support amd64 platforms, but they start from version 9.6. And since Postgres 9.5 has been end of life since early 2021 (version 9 in general is end of life), I don't think there will be amd64 platform updates to our current image. 
To me it looks like we can only solve this ticket by upgrading to Postgres 10 or higher.

**Comment by sabrina-ulbrich** [comment]
@langjoh thanks for your research! I can work without docker for now, but it seems a good idea to upgrade pg for that reason alone that pg 9.5 is not supported anymore. So I closed this issue due to the new one you opened.
