### ISSUE TITLE
Upgrade Elasticsearch to a supported version

### ISSUE THREAD

**Issue by langjoh** [rubymonsters/speakerinnen_liste#1202]
Our current version is 6.7.2 which is not supported since 2020-09-26.
Lowest supported version is 6.8.x (EOL Feb 2022).

Lowest version with AMD64-supported Docker image (for Apple M1 chip) is 6.8.22 . -> https://hub.docker.com/r/amd64/elasticsearch/

**Comment by langjoh** [comment]
@zaziemo elasticsearch Docker image is updated to 6.8.22 in current PR, once it works for Sabrina we can merge it

**Comment by zaziemo** [comment]
@langjoh great! I will open a new issue to update elastic again in January ...

**Comment by langjoh** [comment]
@zaziemo We can use this ticket: #1213
Turns out elasticsearch 7.17.0 is the oldest version that works for Docker on new Apple laptops .

**Comment by zaziemo** [comment]
Copied from a duplicate ticket:
This fixes https://github.com/rubymonsters/speakerinnen_liste/issues/1206 (Docker setup for newer Apple laptops).
This will be a breaking change 🙀
https://www.elastic.co/guide/en/elasticsearch/reference/7.0/breaking-changes-7.0.html#breaking_70_mappings_changes

**Comment by zaziemo** [comment]
we currently get that error during indexing:
```
      {
         "index":{
            "_index":"speakerinnen_liste_application_development",
            "_type":"_doc",
            "_id":"39",
            "status":400,
            "error":{
               "type":"illegal_argument_exception",
               "reason":"Contexts are mandatory in context enabled completion field [lastname.suggest]"
            }
         }
      },
      {
         "index":{
            "_index":"speakerinnen_liste_application_development",
            "_type":"_doc",
            "_id":"40",
            "status":400,
            "error":{
               "type":"illegal_argument_exception",
               "reason":"Contexts are mandatory in context enabled completion field [lastname.suggest]"
            }
         }
      },
      {
         "index":{
            "_index":"speakerinnen_liste_application_development",
            "_type":"_doc",
            "_id":"41",
            "status":400,
            "error":{
               "type":"illegal_argument_exception",
               "reason":"Contexts are mandatory in context enabled completion field [lastname.suggest]"
            }
         }
      },
      {
         "index":{
            "_index":"speakerinnen_liste_application_development",
            "_type":"_doc",
            "_id":"42",
            "status":400,
            "error":{
               "type":"illegal_argument_exception",
               "reason":"Contexts are mandatory in context enabled completion field [lastname.suggest]"
            }
         }
      },
```

Apparently there is a problem with the context[:state] if state is not set in a profile.
We could eliminate errors in the specs by adding a state attribute to every profile created in the factory. However this is not what we want, since it should be possible to be found / indexed if no state is given.

We have to investigate the definition of `contexts[:state] = current_region if current_region` in `searchable.rb` or specifically how the `current_region` is set.

**Comment by sabrina-ulbrich** [comment]
@zaziemo @langjoh As far as I understand the change of the new version is that the context has to be set. In our case the context state is nil if current region is not `vorarlberg`. `current_region` is set inside of the application controller: if the request.host has `vorarlberg` as a part, then `current_region` has this value (`vorarlberg`), otherwise it is nil. Maybe a solution is to set `contexts[:state]` inside of self.typeahead (searchable.rb) to some other value than nil or `vorarlberg` - but this seems a bit messy to me (because the naming is only to get elasticsearch work). Maybe @netagonen has another idea to fix this problem. She got this feature working.

**Comment by zaziemo** [comment]
We tried to set the context like this 
`contexts[:state] = current_region ? current_region : 'other'`
but the error stays the same

**Comment by zaziemo** [comment]
Documentation of context suggester: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-suggesters.html#context-suggester

**Comment by zaziemo** [comment]
we decided to do the upgrade without the context suggester because we did not manage to solve the related issues.

**Comment by langjoh** [comment]
good job, the 'make seed' command works now on M1! 👍
