### ISSUE TITLE
twitter callback if cancel is selected

### ISSUE THREAD

**Issue by sray** [rubymonsters/speakerinnen_liste#271]
Action 'failure' seems to be not implemented yet.

How to reproduce the problem:
1) click on "Log in"
2) click on "sign in with twitter"
... Twitter asks to authorize speakerinnen ...
3) click on "cancel"
... Twitter confirms that I have not been authorized and offers me a button "Return to Speakerinnenliste" ...
4) click on button "Return to Speakerinnenliste" produces:
![screenshot from 2014-07-07 16 01 13](https://cloud.githubusercontent.com/assets/1809538/3496160/3f40b226-05df-11e4-850d-bc08ca705ae5.png)

**Comment by netagonen** [comment]
We tried to reproduce the bug, we got to an error page after clicking on "go back to speakerinnen". Is this the bug? Should the error page not be there or it something else?

**Comment by zaziemo** [comment]
@netagonen the expected behaviour would be to get right back to the homepage of speakerinnen.org if you click on the button. You shouldn't see the error page. This works if I click on the Link below, but not if I click on the button. 

<img width="1230" alt="Twitter___Autorisiere_eine_Applikation" src="https://user-images.githubusercontent.com/2119496/79040786-557ce180-7beb-11ea-9894-9ad4df8fbc8b.png">

**Comment by alonpeer** [comment]
✋ I can take a look at this bug.

**Comment by zaziemo** [comment]
Thanks @alonpeer, works as expected :)
