### ISSUE TITLE
translate speakerinnen.org into french

### ISSUE THREAD

**Issue by zaziemo** [rubymonsters/speakerinnen_liste#360]
We want to translate the site into more languages, @madny works on the french translation

**Comment by tyranja** [comment]
Yeay, French. Thanks for the effort @madny !!!!

**Comment by zaziemo** [comment]
What needs to be translated is:
- (de)_yml
- static sites about.(de).html.erb, faq.(de).html.erb, impressum.(de).html.erb

**Comment by zaziemo** [comment]
status: translation is there must only be added to the code.

**Comment by dmarcoux** [comment]
Any progress on this? I am asking as I could translate most of the Strings since my mother language is French.

**Comment by zaziemo** [comment]
@dmarcoux thx a lot for the offer. We already have all the translations but have to transform it into the proper .yml format and add it to the app ;)

**Comment by abelards** [comment]
Hello, how might we help on this?
We are several french people from RailsGirlsParis and I'd love to help for 24 pull requests :)
Cheers,

**Comment by zaziemo** [comment]
Hey @abelards that sounds great :))

What we have right now is the de.yml translated into french https://gist.github.com/zaziemo/5abbaafbff7bc21ba5c6

*the german terms must be deleted 
*the document has to be transfered into the right format .yml
*import the french versions of devise.yml / kaminari.yml / languages.yml / rails.yml 
*implement a "fr" link on the homepage to switch to french locale
*add fields for french main topic and biographie
*optional: the static sites about.(de).html.erb, faq.(de).html.erb, impressum.(de).html.erb have to be translated

**Comment by abelards** [comment]
Hi! Some comments:

"Hast Du etwas Interessantes zu erzählen?" => I'd change that "?" for a "!"
I find that this simple change helped me get much more beginner speakers at @parisrb

> What we have right now is the de.yml translated into french
> https://gist.github.com/zaziemo/5abbaafbff7bc21ba5c6
I contributed to it, I hope you see it, I'm not used to (secret) gists.
Also added or removed some whitespace, went "vouvoiement" instead of "tutoiement" because I feel super weird when a websites tells me "tu" instead of "vous",
and changed some words I've seen in many FR projects and some idioms that sounded awkward :
- éditer -> modifier
- annuler (means cancel) -> supprimer (means delete/destroy)
Also there are <p> in some german text but it's removed in FR. I did not add them back.

Replaced `<a href='http://railsgirlsberlin.de', target='_blank'>Rails Girls</a>` 
by `<a href="http://railsgirls.com">Rails Girls</a>`

Replaced `entraîneurs` (coaches but also pimps -- sorry) by `mentors`.

`devblog: "<a href='http://speakerinnen.wordpress.com/', target='_blank'>Entwicklerinnen-Blog</a>"`
Why the comma after `href`?

>    the german terms must be deleted
>    the document has to be transfered into the right format .yml
Not sure but what should I change specifically? Identation and testing the correctness?

STILL IN TODO
>    import the french versions of devise.yml / kaminari.yml / languages.yml / rails.yml
>    implement a "fr" link on the homepage to switch to french locale
>    add fields for french main topic and biographie
>    optional: the static sites about.(de).html.erb, faq.(de).html.erb, impressum.(de).html.erb have to be translated

Hope it helps, and I may use some more of my 24 days of PR for speakerinnen :) <3

**Comment by zaziemo** [comment]
Wow, @abelards merci beaucoup :)
I will have a look on that later. One small thing right now which is pretty important for the whole translation: we decided to use the "Du" instead of "Sie" in german which would result in a "tu" instead of "vous" in french. We also had discussions about that but finally decided for this tonality in all our documents (mails, tutorials etc.). 
It think we should stick to it if it is "only" your opinion and no cultural no go. I don't mean this as an offence :) But also in Germany it's not common to say "Du" in a buisiness environment, but it is changing more and more and becomes more common in the nice communities :) So probably it's the same in France and we can break a little bit the traditions. But if you recommend not to use "tu" in the french version because it sounds rude and offensive in a business environment it's good to change it.

**Comment by abelards** [comment]
It's certainly not offensive, and not rude, but unusual enough for some to think it bothering.
On the next steps like reformatting the YML I will go back to the "tutoiement": I now know you chose that willfully and after debate so I'll be glad to revert, if only for respect and consistency :)
Most other fixes were typos and slight grammatical fixes so yay to whoever did the first draft!

<rant>Lastly I'm a bit sad to see so much duplication and I still weep that Rails chose a weird YML format instead of the industry-standard GetText ;)</rant>

**Comment by zaziemo** [comment]
Currently closed until there is a team that wants to take care of it in France.
