### ISSUE TITLE
Team-Seite

### ISSUE THREAD

**Issue by anneroth** [rubymonsters/speakerinnen_liste#420]
siehe Mails dazu

**Comment by zaziemo** [comment]
Politologin, Netzaktivistin und Bloggerin. Ihre Themen: Überwachung,
Innenpolitik, Medien und Feminismus. Sie verdient ihr Geld derzeit als
Referentin im NSA-Untersuchungsausschuss des Bundestages. Im April 2013
hat sie begonnen, [Events zu zählen und darüber zu
bloggen](http://50prozent.noblogs.org/post/2013/04/20/sie-kann-sprechen/):
das war der Ausgangspunkt für die Speakerinnen-Liste.

[@annalist](https://twitter.com/annalist) |
[Blog](https://annalist.noblogs.org)

=======

Political scientist, digital rights activist and blogger. Her topics:
surveillance, domestic policy, media and feminism. She is currently
senior advisor at the parliamentary inquiry on mass surveillance at the
German Bundestag, aka "NSA Inquiry". In April 2013 she started to [count
events and to blog about
them](http://50prozent.noblogs.org/post/2013/04/20/sie-kann-sprechen/)
which later led to the creation of the Speakerinnen project.

[@Anne_Roth](https://twitter.com/Anne_Roth) |
[Blog](https://annalist.noblogs.org/en)

Tyranja hat 2012 mit den RailsGirls (http://railsgirlsberlin.de/)
angefangen zu programmieren. Seitdem arbeitet sie an Speakerinnen.org
und der 50Prozent Seite mit. 2015 kann sie ihr Hobby zum Beruf gemacht
und arbeitet bei TravisCI (https://travis-ci.org/). Wenn ihr die Kinder
und der Sport noch Zeit lassen, ließt sie mit Leidenschaft Science Fiction.

Tyranja started 2012 with the railsgirls (http://railsgirlsberlin.de/)
to programm. Since then she works on speakerinnen.org and 50percent.
2015 she turns the hobby into a profession and started to work at
TravisCI (https://travis-ci.org/). After the kids are gone to bed and
she is still awake, she reads passionately science fiction.

Twitter: _tyranja_

Maren Heltsche ist Projektmanagerin und eine der Entwicklerinnen der
Plattform speakerinnen.org <http://speakerinnen.org>
<http://speakerinnen.org>. Sie ist
leidenschaftliche Ruby on Rails-Entwicklerin in progress, liebt DIY,
Digital Media und Kunst. Sie ist Mit-Herausgeberin des Online-Magazins
ROSEGARDEN und Quartiersleiterin der Digital Media Women Berlin. Ihr
Geld verdient sie als Datenanalystin und Projektmanagerin.

Twitter: @zaziemo | www.rosegarden-mag.de
<http://www.rosegarden-mag.de> <http://www.rosegarden-mag.de>

Maren Heltsche is the project manager and one of the developers of
speakerinnen.org <http://speakerinnen.org>
<http://speakerinnen.org>. Her passions are DIY,
digital media and programming Ruby on Rails with the Railsgirls Berlin.
She is also the co-founder and editor of the online magazine Rosegarden
and head of the local chapter Berlin of the Digital Media Women. Maren
works as a freelance data analyst and project manager.  

Twitter: @zaziemo | www.rosegarden-mag.de
<http://www.rosegarden-mag.de> <http://www.rosegarden-mag.de>

Für den Teamtext:

Schreibende aus Beruf und Leidenschaft. Ihr Geld verdient sie als
Redakteurin und Wort-Beraterin. Wenn sie nicht arbeitet, reist sie am
liebsten dies- und jenseits der Ozeane. Und holt die spannendsten
Städte in ihr Blog-Magazin Naest. Sie hilft bei Fragen der
Speakerinnen weiter, kümmert sich um administrative und
Marketing-Aufgaben.

Naest (www.naest.de <http://www.naest.de>) I Wortspektrum
(www.wortspektrum.de <http://www.wortspektrum.de>)

Writer of profession and passion. She works as an editor and
word-consultant. In her free time she loves to travel the world. The
most exciting cities she brings to her blog-magazine Naest. Christiane
helps with Speakerinnen questions, takes care of adminstrative and
marketing tasks.

Naest (www.naest.de <http://www.naest.de>) I Wortspektrum
(www.wortspektrum.de <http://www.wortspektrum.de>)

**Comment by tyranja** [comment]
Guckt noch mal drüber, ansonst ist es fertig.
