### ISSUE TITLE
build quick and detailed search via elasticsearch

### ISSUE THREAD

**Issue by zaziemo** [rubymonsters/speakerinnen_liste#488]
## Context
Currently speakerinnen.org is using a homegrown postgres search for searching all the profiles and topics. There are two types of search: 
* a quick search (which only searches some fields - fullname, topics, twitter handle) and 
* a detailed search (which searches mostly all fields and makes it possible to search specific content in specific fields).  
See the search working here: https://speakerinnen.org/en/profiles 

Now I want to use elasticsearch to rebuild the search and I already implemented the basic functions of elasticsearch via the elasticsearch-rails gem in this branch: https://github.com/rubymonsters/speakerinnen_liste/tree/zaziemo-elasticsearch

## My questions:
What is the best way to build these two search options with elasticsearch? Specificly:
* How to decide on the best approach to realize the two search options via elasticsearch (e.g. create multiple indeces, use different index types)? 
* Are there examples of similar approaches?

**Comment by eeeebbbbrrrr** [comment]
If you're still using Postgres, checkout @zombodb. This is what it was designed to do.

**Comment by DanielNill** [comment]
👋 
For the simple search you likely want to use `multi_match` https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-multi-match-query.html.

For the field searches you'll likely want to have a terms filter for each field and depending on how precise/loose you want to be provide analyzers for each field for partials and/or synonyms.

so you could have json something like:

```
{
  query: {
    bool: {
      must: [
        # for the simple search
        multi_match: {
          query: args[:simple_search_string],
          fields: [:name, :topics, :twitter]
        },

        # if field is present
        { term: { first_name: args[:name] } },

        # if field is present
        { term: { last_name: args[:city] } },
    
        # etc....
      ]
    }
  }
}  
```

**Comment by eeeebbbbrrrr** [comment]
Here's a little more words about @zombodb (I was on my phone above)...

First, I'd be happy to give you a demo above and beyond what its [TUTORIAL.md](https://github.com/zombodb/zombodb/blob/master/TUTORIAL.md) demonstrates.  What y'all are doing with https://www.speakerinnen.org/ seems pretty great and I'd be happy to help.

ZDB is designed to (mostly) abstract away Elasticsearch.  This means you don't have to worry about synchronizing your remote ES index, don't need to clutter your codebase with an ES-specific API (ie, just keep using your ruby Postgres driver), and also means you get MVCC-correct search results in the face of concurrent updates (thanks to Postgres being amazing).

ZDB has users ranging from a few thousand rows to multi-billion rows.  It's really quite powerful and would probably be very simple to integrate with your website.  It'll definitely handle the two use cases you outlined.

**Comment by Xylakant** [comment]
For the quick search I'd probably either use the `_all` field which would search all indexed content or use the `copy_to` feature to build a field with the relevant content. `multi_match` should work as well, as proposed further above. However, I'd recommend staying away from `terms` queries unless you understand the interactions with the analyser chain (lowercasing, unicode folding etc.), rather use individual `match` queries.

Since you'll be dealing with names and most likely with german language, you'll certainly want to think a lot about analysis. You'll certainly have to take care of handling umlauts - searching for `Müller` should also yield results for `Mueller` and vice versa. Fuzzy and spelling mistakes will be a relevant topic. Another interesting topic for the near future is probably suggest functionality since that helps to prevent most of these spelling issues.

Regarding the index/type setup: I'd expect that a single index with a single type would be the best option.

We @ asquera could give you a short primer on what you need to look out for if you're interested. It's probably a matter of a few hours to cover the most important basics. If you're interested please get in touch.

**Comment by karmi** [comment]
Hi @zaziemo, feel free to ping me via Github issues at https://github.com/elastic/elasticsearch-rails (or https://github.com/elastic/elasticsearch-rails), I'll be glad to help!

(Also, there's a pretty complex demo application with fulltext search, faceted filters, highligting, suggestions, etc available at: https://github.com/elastic/elasticsearch-rails/blob/master/elasticsearch-rails/lib/rails/templates/03-expert.rb -- it's worth checking out to get ideas or see concrete code examples.)

**Comment by BriocheBerlin** [comment]
Hello @zaziemo, I am also working on this. Is there a way I could get the original data for finetuning the results? 
( For learning purposes, not trying to steal this issue from you; I was also there when Jan gave the introduction @ asquera, remember?)

**Comment by zaziemo** [comment]
@BriocheBerlin yes, I remember. Unfortunately we don't give out the original data - privacy reasons.  But you could work with some test profiles you create locally? There are two possibilities to do that:

**Comment by BriocheBerlin** [comment]
@zaziemo I might drop by the monstas today :)

**Comment by zaziemo** [comment]
@Xylakant thanks for your offer to talk. I already set up a meeting with @BriocheBerlin on thursday. Would you be available on that day? Probably you follow me on twitter so we can talk about details via dm.

**Comment by zaziemo** [comment]
short conclusion: we decided not to use the differenciation between quick and detailed search but to use elasticsearch scoring function to prioritize certain fields and to implement a faceted search to filter search results. Thanks @Xylakant & @BriocheBerlin for your support!
