### ISSUE TITLE
make search specs passing again on travisCI 

### ISSUE THREAD

**Issue by zaziemo** [rubymonsters/speakerinnen_liste#553]
current hypothesis: we have to find out on which path elasticsearch is starting on travis and specify this path in spec_helper 
@BriocheBerlin  probably you or one of your colleagues has an idea on that as well!?

**Comment by tyranja** [comment]
Hello @karmi, we are totally stuck in getting our test to run on travis and locally.

**Comment by karmi** [comment]
Hi @tyranja, thanks for pinging me, and sorry for a late response!

The general approach you outline is correct, but somehow the `Test::Cluster` extension is not finding the path to the Elasticsearch launch script, as is indicated from the error: "Cannot find Elasticsearch launch script from [elasticsearch]". I've recreated the environment with the exact SHA1 you're using in your code, to be sure that I work with the same `elasticsearch-extensions` gem version (there has been a lot of changes along), and I think I've found the culprit, and it is a bug in the library.

When I have this code in the helper script:

```ruby
Elasticsearch::Extensions::Test::Cluster.start(
	command: "/tmp/elasticsearch-2.4.5/bin/elasticsearch",
	port: 10000,
) unless Elasticsearch::Extensions::Test::Cluster.running?(port: 9250)
```

and I print out the arguments in the [`Cluster.new`](https://github.com/elastic/elasticsearch-ruby/blob/f769f998c8e5/elasticsearch-extensions/lib/elasticsearch/extensions/test/cluster.rb) method, I'm getting this:

```
{:port=>9250}
{:port=>9250}
/Users/karmi/.bundle/ruby/2.0.0/elasticsearch-ruby-f769f998c8e5/elasticsearch-extensions/lib/elasticsearch/extensions/test/cluster.rb:458:in `__determine_version': No such file or directory - Cannot find Elasticsearch launch script from [elasticsearch] -- did you pass a correct path? (Errno::ENOENT)
```

You can see that the `port` argument has the latter value, and the `command` argument is missing altogether. This is what happens, I believe, in your case. As soon as the `unless ... running?` line is removed, everything behaves correctly. I have to verify why this happens and come up with a fix.

In the meantime, you have two options:

1. If you want to keep the check for a running cluster, initialize the class directly, and use the `start` and `running?` methods on the instance:

```ruby
cluster = Elasticsearch::Extensions::Test::Cluster::Cluster.new(
	command: "/tmp/elasticsearch-2.4.5/bin/elasticsearch",
	port: 10000,
	# ...
) 

cluster.start unless cluster.running?
```

2. You can skip the `running?` check altogether on Travis, because an argument could be made, that it's a blank-slate and disposable environment, so no Elasticsearch should be running before the Rspec's `before :all` helper runs:

```ruby
Elasticsearch::Extensions::Test::Cluster.start(
	command: "/tmp/elasticsearch-2.4.5/bin/elasticsearch",
	port: 9250,
	# ....
)
```

I'd vote for the latter.

Couple of related notes:

* There are [Rake tasks](https://github.com/elastic/elasticsearch-ruby/blob/f769f998c8e551c54cc39135696de7d22f563603/elasticsearch-extensions/lib/elasticsearch/extensions/test/cluster/tasks.rb) available for easy launching a test cluster for development, if you wouldn't be familiar with them. This allows you to launch and _keep running_ Elasticsearch nodes when you develop:

```bash
TEST_CLUSTER_COMMAND=/.../.../bin/elasticsearch bundle exec rake elasticsearch:start
```

* I'm not sure how the "working directory" works on Travis, when you simply do `wget ...` something. So [this is what I prefer to do](https://github.com/elastic/elasticsearch-rails/blob/2.x/.travis.yml#L39) to make sure that Elasticsearch is extracted to a know location:

```
curl -sS https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/tar/elasticsearch/2.4.3/elasticsearch-2.4.3.tar.gz | tar xz -C /tmp
export TEST_CLUSTER_COMMAND=/tmp/elasticsearch-2.4.3/bin/elasticsearch
# ...

```

**Comment by tyranja** [comment]
Hello @karmi Thanks a lot for your answer and all the explanations. Its was super helpful :bouquet: 

I tried the second suggestion and yeay, I get a different error message on travis now. :smile: 
 So your suggestion is working I just have to work on the tests now. 

Thanks again!

**Comment by zaziemo** [comment]
there are new problems with the specs that are running without problems locally.
Apparently the refreshing of the index causes a failure `Faraday::ConnectionFailed: Connection refused - connect(2) for "localhost" port 9200`
@tyranja do you have an idea?

**Comment by karmi** [comment]
@zaziemo, can you post a link to the Travis failure?

**Comment by zaziemo** [comment]
@karmi yes, sure! Here is the link to the failure: https://travis-ci.org/rubymonsters/speakerinnen_liste/builds/238756025

and here the corresponding .travis.yml: https://github.com/rubymonsters/speakerinnen_liste/blob/zaziemo-elasticsearchv2.4-international-iso_languages/.travis.yml

Thanks for your support <3!

**Comment by karmi** [comment]
Hi, I think I've found the culprit, and it might be easy to fix.

So, the error on Travis is that `Faraday::ConnectionFailed ... for "localhost" port 9200`. Therefore, Elasticsearch is expected to be running on port `9200` — which is probably case when you develop locally.

However, in the test setup, you [launch an Elasticsearch cluster on port `9200`](https://github.com/rubymonsters/speakerinnen_liste/blob/zaziemo-elasticsearchv2.4-international-iso_languages/spec/spec_helper.rb#L50). And these two don't match :)

The `elasticsearch` gem [automatically accepts an URL from an `ELASTICSEARCH_URL` environment variable](https://github.com/elastic/elasticsearch-ruby/tree/master/elasticsearch-transport#setting-hosts), so this might be the easiest solution — just set the variable to `http://localhost:9250` on Travis. (Sidenote, it makes sense to launch the test cluster on some other port than the default 9200, otherwise a test run would wipe out all your local data.)

Looking at the Travis configuration, there seems to be a lot of confusion now :), presumably coming from the all the tweaking when trying to make it work. Notice you set `ES_VERSION=2.4.5`, but then have a hard-coded value of `2.4.3` in the rest of the configuration. Can you try this, if it would work on Travis?

```yaml
env:
  - ELASTICSEARCH_URL=http://localhost:9250 ES_VERSION=2.4.5 ES_DOWNLOAD_URL=https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/tar/elasticsearch/${ES_VERSION}/elasticsearch-${ES_VERSION}.tar.gz  TEST_CLUSTER_COMMAND=/tmp/elasticsearch-${ES_VERSION}/bin/elasticsearch

before_install:
  - curl -sS https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/tar/elasticsearch/${ES_VERSION}/elasticsearch-${ES_VERSION}.tar.gz | tar xz -C /tmp
```

Instead of [`sleep 10`](https://github.com/rubymonsters/speakerinnen_liste/blob/zaziemo-elasticsearchv2.4-international-iso_languages/.travis.yml#L18), you could query the cluster state with `curl http://localhost:9250/_cluster/health?wait_for_status=yellow`, which would block until the cluster is at least in a "yellow" state. But since you're launching the cluster for the tests in the RSpec helper, with the `Elasticsearch::Extensions::Test::Cluster` extension, you shouldn't need to do this, since you're not starting Elasticsearch in the Travis steps.

Again, ping me if you'd like to have more assistance!

**Comment by zaziemo** [comment]
Hallelujah! @karmi now it works thx a lot 🎉🎉🎉 https://travis-ci.org/rubymonsters/speakerinnen_liste/builds/239571965
I had to keep sleep instead of the cluster health request which made the build stop.

**Comment by karmi** [comment]
@zaziemo, glad to hear that! 

(And yes, you can't do the `curl` request, since the downloaded Elasticsearch is not started, in fact I wanted to say you shouldn't need the sleep at all :)

**Comment by tyranja** [comment]
Hello @karmi, we are stuck again :/
