### ISSUE TITLE
Make a link to categories on the landing papge

### ISSUE THREAD

**Issue by tyranja** [rubymonsters/speakerinnen_liste#590]
Before we applied the new search we had a link to categories. since 105 our user used categories it would make sense to add that link back.

**Comment by zaziemo** [comment]
but the users also have access to categories via the other section of the homepage.
But nevertheless it's a good idea - we removed the links below the search field because of the readability  of the autofill suggestions. And also because we thought to display the categories on another place of the picture (remember Brigittes suggestion of the new homepage)?

**Comment by tyranja** [comment]
Done!
