### ISSUE TITLE
find more n+1 queries

### ISSUE THREAD

**Issue by zaziemo** [rubymonsters/speakerinnen_liste#724]
use bullet logs and also try to replace .where with .select

**Comment by tyranja** [comment]
a good article about performance: https://www.netguru.co/codestories/activerecord-tips-2

**Comment by sabrina-ulbrich** [comment]
another interesting article about faster active record queries: three slow queries are explained: where, count and present?
https://www.speedshop.co/2019/01/10/three-activerecord-mistakes.html

**Comment by alonpeer** [comment]
Hi 👋 
I'm working on getting rid of n+1 queries on the profiles index page, based on data from the bullet logs (it's really great and helpful!).
I realised that, since for each profile we display their list of topics, it uses [this method](https://github.com/rubymonsters/speakerinnen_liste/blob/master/app/helpers/profiles_helper.rb#L25-L27), which takes the list of topics of the profile and fetches the locale translations for them. This creates n+1 queries - for each profile in the view (e.g. 24 when we browse all profiles), it queries the DB for the translations of the topics for that profile.
I'm wondering whether or not to try and fix this, or maybe I should leave this alone. @netagonen suggested I ask, because this whole view might change in the new website version. @tyranja, WDYT?
