### ISSUE TITLE
A new error page

### ISSUE THREAD

**Issue by tyranja** [rubymonsters/speakerinnen_liste#881]
At the moment it looks like that:
![error_page](https://user-images.githubusercontent.com/1218914/52970884-b75e0480-33b5-11e9-8892-78c241d564b3.png)

There is room for improvement I think :laughing:

**Comment by netagonen** [comment]
To dos:
translate the yml keys to German
resolve the blogpost part
resolve the footer part
resolve the log-in part

**Comment by zaziemo** [comment]
<%= render 'layouts/footer' if render_footer? %>

**Comment by netagonen** [comment]
I have some progress :)

First, if you want to see it locally , when on my branch, go to `config/environments/development` and change the `true` to `false` in the line: `config.consider_all_requests_local` so you will have `config.consider_all_requests_local = false'. But don’t commit it because we need this to be true on development in general, and then It works only on production and staging.

Second, could someone go over the texts please? I copied what was on the default error pages wort for word but maybe we want something else? Some of the custom made pages are more friendly phrased. It's all translated to German with an online translator so I think it would be good if someone checked the German version.

Third, I get for some reason the footer twice:
![Screenshot from 2019-12-02 20-36-23](https://user-images.githubusercontent.com/22200510/69989265-8d8c5d80-1543-11ea-8799-225045683e28.png)
Have any idea why?
