### ISSUE TITLE
Search result without text match

### ISSUE THREAD

**Issue by guerda** [rubymonsters/speakerinnen_liste#927]
Some speakers occur in search results without having a text match. The profile also does not match at all to the search term..

**Steps to reproduce**
1. search for "crypto" or "bitcoin"
2. scroll through list

**Expected results**
Only profiles with that term show up.

**Current results**
Profile of G.R. with "spiritualität" "kreativität" "wertschätzung" appears, no mentions of bitcoin or crypto.

**Comment by zaziemo** [comment]
Hey @guerda, thanks for bringing that up. This is weird indeed. We'll check that!

**Comment by zaziemo** [comment]
Hey @guerda, 
I debugged the elasticsearch results. 
In this case the german language profile has a totally different content than the one in english. If you switch the locale for the profile you can see it. So the matching in the search results works. But seeing the german language profile in the german locale is quite confusing. Since we have no validation for consistency of the profile content we can't avoid such cases. Do you have a user friendly idea how to fix this?

**Comment by zaziemo** [comment]
@guerda one idea from our side: we contacted her and asked her to improve the consistency of her profile.

**Comment by guerda** [comment]
Thank you, Maren, for your quick reply!
This is definitely interesting. I'm not sure why the site was in English, as I'm using a German locale browser etc, but that's not the point :)

Your suggestion is good to keep it consistent. For me as a user I did not know that it's even possible to have two profiles in different languages.
Maybe it would be possible to have a tabbed view of the profiles where you can switch to those languages in which the profile was written? Defaulting to the current locale would be the best.
Then users could see that there's more content and they can decide if they want to see it in German, English, Spanish, Suomi or whatever.

**Comment by zaziemo** [comment]
Hey @guerda we will discuss your idea when updating our search. For now I unpublished the misleading profile (after a contact via email that didn't change anything).
