### ISSUE TITLE
migrate the pics from carriewave aws to active storage

### ISSUE THREAD

**Issue by tyranja** [rubymonsters/speakerinnen_liste#943]

**Comment by sabrina-ulbrich** [comment]
I am wondering how it works with the absolute path because carrierwave and active storage start differently:
- https://speakerinnen-production.s3-eu-central-1.amazonaws.com/uploads/
- https://speakerinnen.org/rails/active_storage/representations/

**Comment by sabrina-ulbrich** [comment]
Next step is to run the rake task on the staging environment.

**Comment by sabrina-ulbrich** [comment]
@tyranja It seems that all pictures are successfully transferred from carrierwave to active storage. You can check it with the edit date 11.11.2019 in admin table. There are some other pictures where the name doesn't correspond to the name at aws, don't know why there are such pics in carrierwave, but I guess all pics with consistent file names are now in sctive storage. Do you have the permission to change the directory name "uploads" to something different on staging? So that we are sure the pictures are shown without access to the old directory. I can't change the name. Btw. a side effect using active storage is some more database ... so now staging is over the limit for the free db plan.

**Comment by sabrina-ulbrich** [comment]
... I was talking about staging

**Comment by sabrina-ulbrich** [comment]
More precisely: There are 4 cases with the pictures (on staging):
- Pictures are transferred (285x), everything paletti, profile has been changed (11.11.2019)
- "exeption: 404 Not Found" (95x) if filename in browser (inspect) and aws do not match (e.g. ID's: 531, 532, 539), looks like that: 
![Screen Shot 2019-11-12 at 00 59 04](https://user-images.githubusercontent.com/372649/68630540-f43fcd80-04e7-11ea-8c62-6358d53a19af.png)

- There is no picture, nothing happens, dummy avatar will still be displayed (e.g. ID's: 446, 452, 534)
- Pictures are already in active storage, nothing happens, picture will still be displayed (e.g. ID's: 3365, 3374, 3388)

**Comment by sabrina-ulbrich** [comment]
done
