### ISSUE TITLE
Notices for empty fields in contact form should be in a more logical spot

### ISSUE THREAD

**Issue by kolja-lucht** [rubymonsters/speakerinnen_liste#951]
When leaving any field in the contact form empty, the user gets a notice `can't be blank`, as shown in this screenshot:
<img width="260" alt="Screenshot 2019-10-19 at 16 48 02" src="https://user-images.githubusercontent.com/6205839/67147165-ab9f4680-f292-11e9-9e21-7e1902b67edd.png">

However, it seems like the notice refers to the field underneath the actual field. A better behaviour would be to have the notice above the corresponding empty field.

**Comment by shen-sat** [comment]
Hi @kolja-lucht I'd like to take on this issue if possible? I've made one contribution to open source before, and I'm learning to use Rails (for over 3 months) in my current job.

**Comment by kolja-lucht** [comment]
Hey @shen-sat! Sure, go ahead. Please make sure to check out the contribution guidelines before you're getting started 🙂 https://github.com/rubymonsters/speakerinnen_liste/blob/master/CONTRIBUTING.md

**Comment by shen-sat** [comment]
Hi @kolja-lucht, apologies for the radio silence on my end! I'm picking up this piece of work now :)

I want to run the project locally, but when I run `bundle install` the install hangs at this line:
`Installing libv8 6.7.288.46.1 with native extensions` and doesn't progress any further (I've tried waiting up to half an hour with no luck).

Have you encountered this problem?

**Comment by kolja-lucht** [comment]
Hey @shen-sat,
it's been a while since I set up the project, but I don't remember running into that kind of issue. 
Does it just get stuck or do you see any errors?

**Comment by zaziemo** [comment]
@shen-sat on what machine are you working and what operating system are you using?
It would also be good to provoke an error message. Probably try `gem install libv8 -v '6.7.288.46.1'`

**Comment by shen-sat** [comment]
Hi, thanks for the prompt replies!

I'm using the macOS Catalina 10.15.1. 

When I run `gem install libv8 -v '6.7.288.46.1'` I don't get any errors, the installation simply hangs. The output to console looks like this:

`> gem install libv8 -v '6.7.288.46.1'
Building native extensions. This could take a while...`

After a while (I've waited up to half an hour) I force quit the install and I get this box popping up:
![image](https://user-images.githubusercontent.com/27900457/71849304-a8656b00-30c9-11ea-97a1-140f0b788fdb.png)

I'be been Googling this since yesterday and tried a few different solutions (including installing v8 via brew and then trying to install the gem via the command: `gem install libv8 -v '6.7.288.46.1' -- --with-system-v8`) - no luck :(

I then tried looking for which gem depends on `libv8` (with the hope of updating that gem which might in turn use an updated version of `libv8`). But when I run `gem dependency`, I don't see `libv8` in the console ouput, so I can't figure wout which gem depends on it 🤔

If you have any suggestions, I'd be happy to try them out. I'm itching to get into the code 😄

**Comment by zaziemo** [comment]
@shen-sat I'm sorry but I'm afraid I can't help you :( We were encountering problems with Catalina and Ruby 2.6.5. before but couldn't solve it. We are currently working on providing a docker image for this project so getting into the code should be easier in the future.

**Comment by Powerglove** [comment]
@shen-sat One possible fix is updating the mini_racer gem https://github.com/rubyjs/libv8/issues/280

**Comment by netagonen** [comment]
@shen-sat, now we have docker and it should fix all these problems :)
Are you still interested on working on this issue? 
Otherwise @Powerglove and I will take it. 
Thanks!

**Comment by shen-sat** [comment]
Hi @netagonen, thanks for the heads up :) I'll try runnning the dockerised version tonight - if it works then I would love to work on this issue. If I still can't build the app then I will hand over to you. Does that sound ok?

**Comment by netagonen** [comment]
Sure! let me know how it goes, thanks!!
