### ISSUE TITLE
Search filters

### ISSUE THREAD

**Issue by netagonen** [rubymonsters/speakerinnen_liste#995]
After a search, search results could be filtered by country, city and language.
Change those filters so they would be take less space in the page and the use can see also some search results, meaning profiles. 
Ideas to how to collapse the filters could be - collapse, side bar, drop down.   
1st step would be to make a decision - to be decided by @salitkrac 
in the implementation consider these tickets as well: https://github.com/rubymonsters/speakerinnen_liste/issues/567 and https://github.com/rubymonsters/speakerinnen_liste/issues/917 if not already implemented

**Comment by tyranja** [comment]
filter via:

- format
- maybe category

**Comment by tyranja** [comment]
![Screenshot from 2020-02-10 20-10-16](https://user-images.githubusercontent.com/1218914/74181328-620fa880-4c41-11ea-96c6-bd528675bc35.png)

**Comment by alonpeer** [comment]
👋 I can try to do this one.

**Comment by alonpeer** [comment]
@tyranja should I work on this from master branch or another one?

**Comment by tyranja** [comment]
Master is fine. Not gonna change much in search. Thank you!!!

Not sure if filtering via category make sense. Because we admins set those categories to the tags and if people are looking for a tag  they probably don't care in which category it is in. 

But filtering with the new attributes `will_be_for_non_profite` and `willing_to_travel` would make sense. So maybe you have to make a branch from Netas branch branch? :man_shrugging:

**Comment by alonpeer** [comment]
Ok I'll discuss this with Neta as well.

**Comment by netagonen** [comment]
Think about implementing together with #994
